
name: moneymate-prod
networks:
  moneymate-network:
    driver: bridge
services:
  gateway:
    build:
      context: .
      dockerfile: ./services/gateway/Dockerfile
      target: prod
    env_file:
      - .env.prod 
    environment:
      - CONFIG_PATH=/config.yaml
      - AUTH_SERVICE_URL=auth:9091
      - REDIS_URL=redis:6379
    ports:
      - "8080:8080" 
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      auth:
        condition: service_started
    networks:
      - moneymate-network

  auth:
    build:
      context: .
      dockerfile: ./services/auth/Dockerfile
      target: prod 
    env_file:
      - .env.prod
    environment:
      - DB_URL=postgres://${AUTH_DB_USER}:${AUTH_DB_PASSWORD}@postgres:5432/${POSTGRES_DB}?search_path=auth
      - REDIS_URL=redis:6379
      - CONFIG_PATH=/config.yaml
    expose:
      - "8081"
      - "9091"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - moneymate-network
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - moneymate-network

    

  redis:
    image: redis:7-alpine
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - moneymate-network
   

volumes:
  postgres_data:
  redis_data:
