-- Give service users CRUD access to all FUTURE tables created in their schema
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO auth_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT USAGE, SELECT ON SEQUENCES TO auth_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO core_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT USAGE, SELECT ON SEQUENCES TO core_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA merchant GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO merchant_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA merchant GRANT USAGE, SELECT ON SEQUENCES TO merchant_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA rewards GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO rewards_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA rewards GRANT USAGE, SELECT ON SEQUENCES TO rewards_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA automation GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO automation_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA automation GRANT USAGE, SELECT ON SEQUENCES TO automation_user;   